### PR TITLE
On branch main Simplify and parameterize

### PR DESCRIPTION
**Pull request by edburns**
modified:   pom.xml
new file:   src/main/aks/openlibertyapplication.yaml
new file:   src/main/docker/Dockerfile
new file:   src/main/docker/Dockerfile-wlp
modified:   src/main/liberty/config/server.xml
modified:   src/main/resources/cafe/web/messages.properties
modified:   src/main/resources/cafe/web/messages_es.properties
modified:   src/main/webapp/index.xhtml

### CODE REVIEW

**Review by majguo — APPROVED** [review]
I believe you will also update the according published article [Deploy a Java application with Open Liberty or WebSphere Liberty on an Azure Kubernetes Service (AKS) cluster](https://docs.microsoft.com/en-us/azure/aks/howto-deploy-java-liberty-app), otherwise the article will break. Right?

**Comment by majguo** [comment]
I also add @m-reza-rahman so he can get chance to take a look as well.

**Comment by edburns** [comment]
Hello @majguo , this PR addresses the necessary update to the article. https://github.com/MicrosoftDocs/azure-docs-pr/pull/159715

**Comment by edburns** [comment]
This is safe to merge, because I put the changes that would invalidate the article in a profile.

**Pull request merged**
